// Models/AiInferenceBenchmarkResult.cs
// Data model for AI inference benchmark results (Microsoft.AI.Foundry.Local).

using System.Text.Json.Serialization;

namespace StreamBench.Models;

/// <summary>
/// Timings and token counts for a single AI inference run.
/// </summary>
public record AiInferenceRun(
    [property: JsonPropertyName("model_load_sec")]      double ModelLoadSec,
    [property: JsonPropertyName("response_time_sec")]   double ResponseTimeSec,
    [property: JsonPropertyName("total_time_sec")]      double TotalTimeSec,
    [property: JsonPropertyName("prompt_tokens")]       int PromptTokens,
    [property: JsonPropertyName("completion_tokens")]   int CompletionTokens,
    [property: JsonPropertyName("tokens_per_second")]   double TokensPerSecond,
    [property: JsonPropertyName("response_text")]       string ResponseText,
    [property: JsonPropertyName("response_preview")]    string ResponsePreview
);

/// <summary>
/// Full AI benchmark result for one device (CPU / GPU / NPU).
/// </summary>
public record AiDeviceBenchmarkResult(
    [property: JsonPropertyName("device_type")]         string DeviceType,
    [property: JsonPropertyName("model_id")]            string ModelId,
    [property: JsonPropertyName("model_alias")]         string ModelAlias,
    [property: JsonPropertyName("execution_provider")]  string ExecutionProvider,
    [property: JsonPropertyName("question1")]           string Question1,
    [property: JsonPropertyName("run1")]                AiInferenceRun Run1,
    [property: JsonPropertyName("question2")]           string Question2,
    [property: JsonPropertyName("run2")]                AiInferenceRun Run2,
    [property: JsonPropertyName("timestamp")]           string Timestamp
);

/// <summary>
/// Aggregated relation metrics by device type.
/// </summary>
public record AiRelationDeviceAggregate(
    [property: JsonPropertyName("device_type")]                  string DeviceType,
    [property: JsonPropertyName("memory_samples")]               int MemorySamples,
    [property: JsonPropertyName("avg_memory_triad_gbps")]        double AvgMemoryTriadGbps,
    [property: JsonPropertyName("ai_samples")]                   int AiSamples,
    [property: JsonPropertyName("avg_ai_warm_tokens_per_second")]double AvgAiWarmTokensPerSecond
);

/// <summary>
/// One local-AI question and answer.
/// </summary>
public record AiRelationQuestionAnswer(
    [property: JsonPropertyName("index")]                        int Index,
    [property: JsonPropertyName("question")]                     string Question,
    [property: JsonPropertyName("answer")]                       string Answer,
    [property: JsonPropertyName("run")]                          AiInferenceRun? Run = null
);

/// <summary>
/// Full local folder relation summary generated by local AI.
/// </summary>
public record AiLocalRelationSummaryResult(
    [property: JsonPropertyName("source_directory")]             string SourceDirectory,
    [property: JsonPropertyName("memory_json_files")]            int MemoryJsonFiles,
    [property: JsonPropertyName("ai_json_files")]                int AiJsonFiles,
    [property: JsonPropertyName("memory_samples")]               int MemorySamples,
    [property: JsonPropertyName("ai_samples")]                   int AiSamples,
    [property: JsonPropertyName("model_id")]                     string ModelId,
    [property: JsonPropertyName("model_alias")]                  string ModelAlias,
    [property: JsonPropertyName("execution_provider")]           string ExecutionProvider,
    [property: JsonPropertyName("device_level_correlation")]     double? DeviceLevelCorrelation,
    [property: JsonPropertyName("device_aggregates")]            IReadOnlyList<AiRelationDeviceAggregate> DeviceAggregates,
    [property: JsonPropertyName("questions")]                    IReadOnlyList<AiRelationQuestionAnswer> Questions,
    [property: JsonPropertyName("timestamp")]                    string Timestamp
);
